FROM python:3.7
RUN mkdir /home/mrcnn 
WORKDIR /home/mrcnn
COPY requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt
COPY . .
RUN python /home/mrcnn/setup.py install
CMD streamlit run app/cell_app.py --server.port 6123
